name: solver
version: 0.0.1
description: A sample genetic algorithm meaning of life question solver
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  math_expressions: '^0.2.0+1'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
